runtime: python311

# Let App Engine auto-detect wsgi.py (NO custom entrypoint)

env_variables:
  # FLATTENED STRUCTURE - settings are now in root
  DJANGO_SETTINGS_MODULE: "settings_production"
  
  # Security & Config
  SECRET_KEY: "7fd*=c%(w6!r%!+9f@viipb8u!-ra15-fjl8&71nz)m@gch=mp"
  DEBUG: "False"
  
  # Database
  DB_PASSWORD: "YourSecurePassword123!"
  CLOUD_SQL_CONNECTION_NAME: "whatsapp-bulk-messaging-480620:asia-southeast1:whatsapp-bulk-db"
  
  # WABot.my Configuration
  WABOT_WEBHOOK_TOKEN: "6bb47e635cd7649c10a503e7032ecff4"
  WABOT_PHONE_NUMBER: "60162107682"
  WABOT_API_URL: "https://app.wabot.my/api"
  WABOT_API_TOKEN: "68a0a10422130"
  WABOT_INSTANCE_ID: "68A0A11A89A8D"

  
  # API Keys (Optional)
  WHATSAPP_API_KEY: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""

beta_settings:
  cloud_sql_instances: "whatsapp-bulk-messaging-480620:asia-southeast1:whatsapp-bulk-db"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

resources:
  cpu: 0.5
  memory_gb: 0.5

handlers:
- url: /static
  static_dir: staticfiles
  secure: always

- url: /.*
  script: auto
  secure: always