runtime: python311
env: standard

# Basic handlers
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

# Environment variables
env_variables:
  DJANGO_SETTINGS_MODULE: "whatsapp_bulk.settings_production"
  SECRET_KEY: "your-secret-key-here-change-this-in-production"
  DEBUG: "False"
  ALLOWED_HOSTS: "*.appspot.com,whatsapp-bulk-messaging-473607.as.r.appspot.com"
