# Cloud Build configuration for automatic deployment
steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Collect static files
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['manage.py', 'collectstatic', '--noinput', '--settings=whatsapp_bulk.settings_gcp']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

  # Run database migrations (optional - can be done manually)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet', '--version=${SHORT_SHA}-migration', '--no-promote']

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1600s'
