# Cloud Build configuration for deploying with migrations
steps:
  # Step 1: Build and deploy the app
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--project=${PROJECT_ID}'
    timeout: 900s

  # Step 2: Run database migrations via Cloud Run Job
  # Note: This requires Cloud SQL Proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up Cloud SQL Proxy..."
        
        # Download Cloud SQL Proxy
        wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # Start Cloud SQL Proxy in background
        ./cloud_sql_proxy -instances=${_CLOUD_SQL_CONNECTION}=tcp:5432 &
        PROXY_PID=$!
        
        # Wait for proxy to be ready
        sleep 10
        
        # Install dependencies
        pip3 install --user Django psycopg2-binary
        
        # Set environment variables for production settings
        export DJANGO_SETTINGS_MODULE=settings_production
        export DB_PASSWORD=${_DB_PASSWORD}
        export CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION}
        export SECRET_KEY=${_SECRET_KEY}
        
        # Run migrations
        python3 migrate_db.py
        
        # Stop proxy
        kill $PROXY_PID || true
        
        echo "✅ Migrations completed!"
    timeout: 300s

substitutions:
  _CLOUD_SQL_CONNECTION: 'whatsapp-bulk-messaging-480620:asia-southeast1:whatsapp-bulk-db'
  _DB_PASSWORD: 'P@##w0rd'
  _SECRET_KEY: '7fd*=c%(w6!r%!+9f@viipb8u!-ra15-fjl8&71nz)m@gch=mp'

timeout: 1200s
