# Generated by Django 5.2.4 on 2025-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_contest_conversation_contest_contestentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Address extracted from OCR', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_receipt_date',
            field=models.DateTimeField(blank=True, help_text='Date of last receipt processed', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nric',
            field=models.TextField(blank=True, help_text='NRIC extracted from OCR', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='OCR confidence score', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='products_purchased',
            field=models.JSONField(blank=True, default=list, help_text='Products purchased from receipt OCR'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_location',
            field=models.TextField(blank=True, help_text='Store location from receipt OCR', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_name',
            field=models.TextField(blank=True, help_text='Store name from receipt OCR', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount spent from receipt', max_digits=10, null=True),
        ),
    ]
