# Generated by Django 5.2.4 on 2025-09-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_customer_address_customer_last_receipt_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contestentry',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='contestentry',
            unique_together={('contest', 'customer')},
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_instructions',
            field=models.TextField(blank=True, help_text='Instructions for contestants', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='eligibility_message',
            field=models.TextField(default='Congratulations! You are eligible to participate in this contest. Please follow the instructions to complete your entry.', help_text='Message sent when contestant is verified as eligible'),
        ),
        migrations.AddField(
            model_name='contest',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='post_pdpa_gif_url',
            field=models.URLField(blank=True, help_text='GIF URL for post-PDPA message', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='post_pdpa_image_url',
            field=models.URLField(blank=True, help_text='Image URL for post-PDPA message', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='post_pdpa_text',
            field=models.TextField(blank=True, help_text='Text message sent after PDPA consent', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='requires_nric',
            field=models.BooleanField(default=True, help_text='Require NRIC for participation'),
        ),
        migrations.AddField(
            model_name='contest',
            name='requires_receipt',
            field=models.BooleanField(default=True, help_text='Require proof of purchase'),
        ),
        migrations.AddField(
            model_name='contest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='verification_instructions',
            field=models.TextField(blank=True, help_text='Instructions for verification process', null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='additional_documents',
            field=models.JSONField(blank=True, default=list, help_text='Additional document URLs'),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='contestant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='contestant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='contestant_nric',
            field=models.CharField(blank=True, help_text='NRIC number for verification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='contestant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='receipt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Receipt amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='receipt_date',
            field=models.DateTimeField(blank=True, help_text='Receipt date', null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='receipt_image_url',
            field=models.URLField(blank=True, help_text='Receipt image URL', null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='receipt_store',
            field=models.CharField(blank=True, help_text='Store name from receipt', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('winner', 'Winner')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Verification notes', null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Who verified this entry', max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='contestentry',
            name='notes',
        ),
    ]
