# Generated by Django 5.2.4 on 2025-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_contest_options_alter_contestentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='provider',
            field=models.TextField(choices=[('wabot', 'WABot'), ('meta', 'Meta Business API'), ('twilio', 'Twilio')], default='wabot'),
        ),
    ]
