# Generated by Django 5.2.4 on 2025-09-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_contest_message_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='agreement_message',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_introduction',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='failure_message',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='instruction_image',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='pdpa_url',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rejection_message',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='submission_requirements',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='success_message',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='welcome_message',
        ),
    ]
