# Generated by Django 5.2.4 on 2025-10-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_remove_contest_agreement_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participant_agreement',
            field=models.TextField(blank=True, help_text='Message sent when participant agrees to PDPA', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_rejection',
            field=models.TextField(blank=True, help_text='Message sent when participant rejects PDPA', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='pdpa_message',
            field=models.TextField(blank=True, help_text='PDPA consent message sent to participants', null=True),
        ),
    ]
