# Generated by Django 5.2.4 on 2025-10-21 20:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_add_pdpa_consent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='manual', help_text='Source of group: manual, import, contest', max_length=50)),
                ('import_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(blank=True, help_text='Linked contest if source is contest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_groups', to='messaging.contest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='messaging.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlastCampaign',
            fields=[
                ('blast_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('message_text', models.TextField(help_text='Message to be sent to recipients')),
                ('message_image_url', models.URLField(blank=True, help_text='Optional image URL', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_contests', models.ManyToManyField(blank=True, help_text='Target contest participants', related_name='blast_campaigns', to='messaging.contest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_campaigns', to='messaging.tenant')),
                ('whatsapp_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_campaigns', to='messaging.whatsappconnection')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='blast_campaigns', to='messaging.customergroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlastRecipient',
            fields=[
                ('recipient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blast_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.blastcampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_recipients', to='messaging.customer')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_recipients', to='messaging.coremessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_recipients', to='messaging.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('blast_campaign', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Custom data for this member')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='messaging.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.customergroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='messaging.tenant')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('group', 'customer')},
            },
        ),
    ]
