# Khind Merdeka W2 Contest Data - Complete Dataset (199 entries)
KHIND_MERDEKA_W2_DATA = [
    {
        'submission_no': 'MLP_202',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM320.00',
        'store': 'LIAN HONG TRADING',
        'store_location': 'KOTA BHARU, KELANTAN',
        'product_purchased_1': 'RC118M',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'MOHD ZUFRI BIN MAT RADZI',
        'phone_number': '60145000000',
        'email': 'nikazlin.anuar38@gmail.com',
        'address': 'PT 258, Kampung Tanjung Bunut Susu',
        'postcode': '17000',
        'city': 'Pasir Mas',
        'state': 'Kelantan',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_7e57dc2b-96fb-4663-9601-e97e17036cd9.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 12:16',
    },
    {
        'submission_no': 'MLP_203',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM90.00',
        'store': 'LIAN HONG TRADING',
        'store_location': 'KOTA BHARU, KELANTAN',
        'product_purchased_1': 'TF166',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'NORAIDA BINTI HUSAIN',
        'phone_number': '60179000000',
        'email': 'nikazlin.anuar38@gmail.com',
        'address': 'c13-17 perumahan ppr',
        'postcode': '15300',
        'city': 'kota bharu',
        'state': 'Kelantan',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_4779_3ee1484a-5e19-4abf-9abd-7c05a933bb8b.jpeg',
        'how_heard': 'Friends/Family Recommendation',
        'submitted_date': '12/8/2025 12:18',
    },
    {
        'submission_no': 'MLP_204',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM82.00',
        'store': 'LIAN HONG TRADING',
        'store_location': 'KOTA BHARU, KELANTAN',
        'product_purchased_1': 'RC810N',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'NIK AZLIN BINTI NIK ANUAR',
        'phone_number': '60145000000',
        'email': 'nikazlin.anuar38@gmail.com',
        'address': 'PT 258, Kampung Tanjung Bunut Susu',
        'postcode': '17000',
        'city': 'Pasir Mas',
        'state': 'Kelantan',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_4778_5ee6da55-fa9b-45c4-9db6-462f87adbfdb.jpeg',
        'how_heard': 'Billboard',
        'submitted_date': '12/8/2025 12:20',
    },
    {
        'submission_no': 'MLP_205',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM249.00',
        'store': 'HOMEPRO',
        'store_location': 'MUTIARA DAMANSARA, SELANGOR',
        'product_purchased_1': 'CF56DC3RL',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Toh Kue Chin',
        'phone_number': '60122978438',
        'email': 'kuechin@gmail.com',
        'address': 'F-3-10 Pelangi Utama Jalan Masjid PJU 6A',
        'postcode': '47400',
        'city': 'Petaling Jaya',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_9007_ad98cfe3-173b-43e8-a328-77f8ec835076.jpeg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 12:23',
    },
    {
        'submission_no': 'MLP_206',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM189.00',
        'store': 'HOMEPRO',
        'store_location': 'MUTIARA DAMANSARA, SELANGOR',
        'product_purchased_1': 'CF56DC1R',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Toh Kue Chin',
        'phone_number': '60122978438',
        'email': 'kueching@gmail.com',
        'address': 'F-3-10 Pelangi Utama Jalan Masjid PJU 6A',
        'postcode': '47400',
        'city': 'Petaling Jaya',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_9008_08fe0021-7af2-40d6-a9df-7b2939b81107.jpeg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 12:24',
    },
    {
        'submission_no': 'MLP_207',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM85.00',
        'store': 'KEMUDI TIMUR',
        'store_location': 'KOTA BHARU, KELANTAN',
        'product_purchased_1': 'BL601P',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'DINA MARIANA',
        'phone_number': '60104184183',
        'email': 'cikatikah581@gmail.com',
        'address': 'LOT 3880 KAMPUNG KUBANG BATANG',
        'postcode': '16250',
        'city': 'WAKAF BHARU',
        'state': 'Kelantan',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_5d37a09d-4e42-4f7b-9b34-f8119aa01069.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 12:49',
    },
    {
        'submission_no': 'MLP_208',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM190.00',
        'store': 'KUANG HUAT ELECTRICAL SALES AND SERVICES',
        'store_location': 'KAMPAR, PERAK',
        'product_purchased_1': 'ICK-IC-2023',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Satbir Kaur',
        'phone_number': '60194774281',
        'email': 'satbir_87@hotmail.com',
        'address': 'No 27, Jalan Putra Berlian 3, Kampar Putra',
        'postcode': '31900',
        'city': 'Kampar',
        'state': 'Perak',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_004f96b1-dab6-4c16-a78b-f39b8354397f.jpg',
        'how_heard': 'Social Media/Online Advertisement, Friends/Family Recommendation, In-store Display',
        'submitted_date': '12/8/2025 12:55',
    },
    {
        'submission_no': 'MLP_209',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM129.00',
        'store': 'AEON',
        'store_location': 'CHERAS, KL',
        'product_purchased_1': 'KHIND CEILING F',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Azman Ahmad',
        'phone_number': '60192244552',
        'email': 'salman68@gmail.com',
        'address': 'No 30 lorong serampang 4b',
        'postcode': '41100',
        'city': 'Klang',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_539f9264-17cf-4f0a-a902-986ae029e97b.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 13:06',
    },
    {
        'submission_no': 'MLP_210',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM580.00',
        'store': 'DIVA LIGHTING',
        'store_location': 'SANDAKAN, SABAH',
        'product_purchased_1': 'FZ100S BR',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Connie Lu Khom Lee',
        'phone_number': '60128100060',
        'email': 'connie_onon@yahoo.com',
        'address': 'Taman pertama Lot 242 Batu 5',
        'postcode': '90000',
        'city': 'Sandakan',
        'state': 'Sabah',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_2019_14000b34-8ae7-46dc-829f-fd0b8a41999e.jpeg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 13:10',
    },
    {
        'submission_no': 'MLP_211',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM155.00',
        'store': 'DIVA LIGHTING',
        'store_location': 'SANDAKAN, SABAH',
        'product_purchased_1': 'RC728',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Connie Lu Khom Lee',
        'phone_number': '60128100060',
        'email': 'connie_onon@yahoo.com',
        'address': 'Taman pertama Lot 242 Batu 5 sandakan',
        'postcode': '90000',
        'city': 'Sandakan',
        'state': 'Sabah',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/IMG_2020_34e7e711-87e2-4dac-8d7c-1bf9955f53f8.jpeg',
        'how_heard': 'In-store Display',
        'submitted_date': '12/8/2025 13:13',
    },
    {
        'submission_no': 'MLP_253',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM1,260.00',
        'store': 'THREE STAR AIR-CONDITIONER TRADING',
        'store_location': 'TAMAN SERI MANGGA, MELAKA',
        'product_purchased_1': 'WM70A',
        'amount_purchased_1': '1',
        'product_purchased_2': 'RF165',
        'amount_purchased_2': '1',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Pauline Ng Wei Shan',
        'phone_number': '60166185519',
        'email': 'pauline.ng1314@gmail.com',
        'address': 'A-6-13A, Admiral residence,jln klj 2,taman kota laksamana Jaya',
        'postcode': '75200',
        'city': 'Melaka',
        'state': 'Melaka',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/1000202657_685ec133-3505-4e0b-8a11-d449c29caa65.jpg',
        'how_heard': 'Friends/Family Recommendation',
        'submitted_date': '14/8/2025 11:02',
    },
    {
        'submission_no': 'MLP_263',
        'validity': 'invalid',
        'reason': 'INVALID PROOF OF PURCHASE',
        'amount_spent': '-',
        'store': '-',
        'store_location': '-',
        'product_purchased_1': '-',
        'amount_purchased_1': '',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Chong Pei yee',
        'phone_number': '60162018649',
        'email': 'cpyee0703@gmail.com',
        'address': 'Tb1604 taman melody batu 3 Jalan apas',
        'postcode': '91000',
        'city': 'Tawau',
        'state': 'Sabah',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_704649f4-8f81-43f5-9af5-e088f16710b3.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '14/8/2025 14:27',
    },
    {
        'submission_no': 'MLP_272',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM424.00',
        'store': 'KHIND CUSTOMER SERVICE',
        'store_location': 'SHAH ALAM, SELANGOR',
        'product_purchased_1': 'VC9675MS',
        'amount_purchased_1': '1',
        'product_purchased_2': 'RC106M',
        'amount_purchased_2': '1',
        'product_purchased_3': 'RC118M',
        'amount_purchased_3': '1',
        'full_name': 'nazimmudin bin zulkifli',
        'phone_number': '60142272097',
        'email': 'nazimmudinzulkifli@gmail.com',
        'address': 'no 13 lorong gugusan alam 7/20',
        'postcode': '42300',
        'city': 'bandar puncak alam',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_6eca0c46-ac7b-4a9e-800d-067d8e053747.jpg',
        'how_heard': 'Friends/Family Recommendation',
        'submitted_date': '15/8/2025 10:41',
    },
    {
        'submission_no': 'MLP_340',
        'validity': 'duplicate',
        'reason': 'DUPLICATE OF MLP_339',
        'amount_spent': '-',
        'store': '-',
        'store_location': '-',
        'product_purchased_1': '-',
        'amount_purchased_1': '-',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'Beh Meng Poh',
        'phone_number': '60193195549',
        'email': 'ahpoh5304@gmail.com',
        'address': 'No 30, Jalan Angkasa 1C/6, Bandar mahkota Banting',
        'postcode': '42700',
        'city': 'Banting',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/27567_7cd71dcd-6e0e-4626-bb3e-057c90204a02.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '17/8/2025 14:57',
    },
    {
        'submission_no': 'MLP_378',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM219.00',
        'store': 'KHIND CUSTOMER SERVICE',
        'store_location': 'SHAH ALAM, SELANGOR',
        'product_purchased_1': 'VC1525EX',
        'amount_purchased_1': '3',
        'product_purchased_2': 'ZV807EX',
        'amount_purchased_2': '1',
        'product_purchased_3': 'BH600M',
        'amount_purchased_3': '1',
        'full_name': 'KHOO MEI YEE',
        'phone_number': '60193568399',
        'email': 'metta_my@yahoo.com',
        'address': '10, Jalan Menara U8/8 Bukit Jelutong',
        'postcode': '40150',
        'city': 'Shah Alam',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/image_2c05f9da-a61b-4dbf-b38c-783df1a0baf9.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '18/8/2025 11:55',
    },
    {
        'submission_no': 'MLP_400',
        'validity': 'valid',
        'reason': '',
        'amount_spent': 'RM109.99',
        'store': 'AEON BIG',
        'store_location': 'SUBANG JAYA, SELANGOR',
        'product_purchased_1': 'RCJ1809',
        'amount_purchased_1': '1',
        'product_purchased_2': '',
        'amount_purchased_2': '',
        'product_purchased_3': '',
        'amount_purchased_3': '',
        'full_name': 'AMANINA ALIAH BINTI HASAN RIJAL',
        'phone_number': '60176545884',
        'email': 'amaninaaliahhr@gmail.com',
        'address': 'No 18 Lorong Sungai Puloh 7, Taman Cempaka Sari 3',
        'postcode': '42100',
        'city': 'Klang',
        'state': 'Selangor',
        'receipt_url': 'https://form-builder-by-hulkapps.s3.amazonaws.com/uploads/khindmarketing.myshopify.com/store_image/1000238222_c4c8b505-8f1e-467e-b6d5-546ed4aa1983.jpg',
        'how_heard': 'In-store Display',
        'submitted_date': '18/8/2025 20:58',
    }
]
