name: Deploy to Google Cloud Platform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: whatsapp-bulk-messaging-473607
  SERVICE: default
  REGION: us-central

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ env.PROJECT_ID }}
        gcloud config set app/cloud_build_timeout 1600

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput --settings=whatsapp_bulk.settings_gcp

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet --version=${{ github.sha }} --no-promote

    - name: Run database migrations
      run: |
        gcloud app deploy --quiet --version=${{ github.sha }}-migration --no-promote
        # Note: You'll need to run migrations manually or set up a Cloud SQL proxy

    - name: Promote new version
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        gcloud app services set-traffic ${{ env.SERVICE }} --splits=${{ github.sha }}=1

    - name: Get App URL
      run: |
        echo "App deployed at: https://${{ env.PROJECT_ID }}.appspot.com"
